server:
  port: 8881
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demosecurity
    username: root
    password: 123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
